name: Release CI

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          # Disabling shallow clone is needed for correctly determining next release with semantic release
          fetch-depth: 0
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build
        run: mvn -B package

      - name: Release
        uses: softprops/action-gh-release@v2
        #if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: keycloak-twitch-idp/target/*.jar
